version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 200M
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/image-processor
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped

  worker:
    build: .
    command: node workers/imageProcessor.js
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 200M
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/image-processor
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local 